application: metcouncilny
version: 0-0-1
runtime: python27
api_version: 1
threadsafe: true

# For now, everything goes to index.html
handlers:
  - url: /.*
    static_files: static/index.html
    upload: static/index\.html